In [62]:
#functions in pandas is less error prone than in numpy b/c pandas will match operations using assigned indices
import pandas as pd
import numpy as np

#create a random state
rng = np.random.RandomState(42)

#create a random pd series
ser = pd.Series(rng.randint(0,10,4))

#create a random pd dataframe
df = pd.DataFrame(rng.randint(0,10,(3,4)),
                 columns = ['A','B','C','D'])

#print(ser)
#apply the exponential function, e^n
np.exp(ser)

#apply a sin(x * pi/4)
#display(df)
np.sin(df * np.pi / 4)

#pandas will do operations based of index. If an index is missing it will skip operation
#for example, New York is only in population and not in area. Doing an operation will cause New York to be nan
area = pd.Series({'Alaska': 1723337, 'Texas': 695662,
                  'California': 423967}, name='area')
population = pd.Series({'California': 38332521, 'Texas': 26448193,
                        'New York': 19651127}, name='population')

area/population

#confirm that the end result is just a union
x = area/population
y = area.index | population.index
x.index == y

#NaN stands for not a number
A = pd.Series([2,4,6], index = [0,1,2])
B = pd.Series([0,2,4], index = [1,2,3])
A+B

#you can change the fill value, but will need to use an explicit function
A.add(B,fill_value = 0)

#similar behaviour can be seen when operating on dataframes
A = pd.DataFrame(rng.randint(0, 20, (2, 2)),
                 columns=list('AB'))

B = pd.DataFrame(rng.randint(0, 10, (3, 3)),
                 columns=['A','B','C'])
A+B

#as before, you can change the fill value for NaN. For example, in this case you treat it as the mean

#display(A)
#A.stack()
fill = A.stack().mean()
A.add(B, fill_value=fill)

#manipulations are done row by row
A = rng.randint(10, size=(3, 4))
A
A - A[0]

#this doe sthe same thing but with a pandas dataframe
df = pd.DataFrame(A, columns=list('QRST'))
df - df.iloc[0]

#if you would like manipulation to be done column wise, you would need to use the method
#get the values in column R and subtract that value in every column of the dataframe
df.subtract(df['R'],axis = 0)

display(df)
#generate a dataframe that only contains every other elements. eg, QS
halfrow = df.iloc[0,::2]
halfrow

df-halfrow

   Q  R  S  T
0  3  8  2  4
1  2  6  4  8
2  6  1  3  8

     Q   R    S   T
0  0.0 NaN  0.0 NaN
1 -1.0 NaN  2.0 NaN
2  3.0 NaN  1.0 NaN